---
title: "Formula"
format: html
---
## Formula used to calculate CO_2 Emission

- $CO_2 = 273 \times \frac{44}{28} * N_2O_{N_{direct}}$

- $N_2O_{N_{direct}} = N_2O_{N_{SNdirect}} + N_2O_{N_{CRNmindirect}} + N_2O_{N_{ONdirect}} + N_2O_{N_{CropResidues}}$

- $N_2O_{N_{CropResidues}} = N_{CropResidues} \times EF$

- $N_{CropResidues} = (AboveGround_{residue\_N} + BelowGround_{residue\_N}) \times {area}$

- $EF = EF_{Base} \times RF\_NS \times RF\_Till \times RF\_CS \times RF\_AM$

### Nitrogen Inputs From Crop Residue Returned To Soil

$$
N_{CropResidues} = (AboveGround_{residue\_N} + BelowGround_{residue\_N})\times area
$$

### Above Ground Residue Nitrogen

For Annual and Perennial Plants,

$$
AboveGround_{residue\_N} = [{Grain_N} + {Straw_N}]
$$

 For Root Plant,

$$
AboveGround_{residue\_N} = {Straw_N}
$$

For Cover and Silage Plant,
$$
AboveGround_{residue\_N} = {Grain_N}
$$

- $Grain_N$ : Nitrogen content of the grain returned to the soil (kg N/ha)

- $Straw_N$ : Nitrogen content of the straw returned to the soil (kg N/ha)

### Below Ground Residue Nitrogen

For annual plants:

$$
BelowGround_{{residue_N}} = [{Root_N} + {Exudate_N}]
$$

For perennial plants:

$$
BelowGround_{residue_N} = [\frac{S_r}{100} \times {Root}_N] + {Exudate_N}
$$

For root plant,
$$
BelowGround_{residue_N} = {Grian_N} + {Exudate_N}
$$

For cover and silage plant,

$$
BelowGround_{residue_N} = {Root_N} + {Exudate_N}
$$

**Variables**:

- $Root_N$ : Nitrogen content of the roots returned to the soil (kg N/ha)

- $Exudate_N$ : Nitrogen content of the exudates returned to the soil (kg N/ha)

- $Grain_N$ : Nitrogen content of the grains returned to the soil (kg N/ha)

### Nitrogen Content Returned To The Soil

- ${Grain}_N = \frac{C_{p\_to\_soil}}{0.45} \times \frac{N_p}{1000}$

- ${Straw}_N = \frac{C_s}{0.45} \times \frac{N_s}{1000}$

- ${Root}_N = \frac{C_r}{0.45} \times \frac{N_r}{1000}$

- ${Exudate}_N = \frac{C_e}{0.45} \times \frac{N_e}{1000}$

**Variables**:

- $C_{p\_to\_soil}$ : Carbon input from products (kg/ha) 

- $C_p$: Plant C (carbon) in agricultural product (kg/ha) 

- $C_s$: C (carbon) input from straw (kg/ha)

- $C_r$: C (carbon) input from roots (kg/ha)

- $C_e$: C (carbon) input from extra-root material (kg/ha)

- $N_p$: Nitrogen concentration in the product (kg N/kg)

- $N_s$: Nitrogen concentration in the straw (kg N/kg)

- $N_r$: Nitrogen concentration in the root (kg N/kg)

- $N_e$: Nitrogen concentration in the extraroots (kg N/kg)

### Carbon Input

- $C_{p\_to\_soil} = C_p \times \frac{S_p}{100}$

- $C_p = [(yield + yield * \frac{S_p}{100}) * (1 - \frac{{moisture \ content}}{100})] * {Carbon \ concentration}$

- $C_s = C_p \times \frac{R_s}{R_p} \times \frac{S_s}{100}$

- $C_r = C_p \times \frac{R_r}{R_p} \times \frac{S_r}{100}$

- $C_e = C_p \times \frac{R_e}{R_p}$

**Variables**:

- yield is defined by users

- moisture content is default based on the crop type

- Carbon concentration is default based on the crop type

- $S_p$: Percentage of product yield returned to soil (%)

- $S_s$: Percentage of straw yield returned to soil (%)

- $S_r$: Percentage of root yield returned to soil (%)

- $R_p$: Relative biomass allocation coefficient for product

- $R_s$: Relative biomass allocation coefficient for straw

- $R_r$: Relative biomass allocation coefficient for root

- $R_e$: Relative biomass allocation coefficient for extra-root


### Emission Factor 

For humid environment:$P > PE$

$$
EF_{{CT}_{P}} = \exp^{0.00558 \times P - 7.7}
$$

$$
EF_{Topo} = EF_{{CT}_{P}}
$$

For dry environment $PE \geq P$

$$
EF_{{CT}_{PE}}= \exp^{0.00558 \times PE - 7.7}
$$ 

**Variables**:

- P: Annual growing season precipitation (May – October) (mm)
- PE: Annual growing season potential evapotranspiration (May – October) (mm)

$$
EF_{Topo} = (EF_{{CT}_{PE}} \times FR_{Topo}) + [EF_{{CT}_{P}} \times (1 - FR_{Topo})]
$$

For irrigated sites, the assumption is that the irrigation amount is equal to PE - P, thus making P = PE, 

$$
EF_{Topo} = EF_{{CT}_{PE}} 
$$ 

**Variables**:

- $FR_{Topo}$: Fraction of land occupied by lower portions of landscape based on ecodistrict
 

$$
EF_{Base} = (EF_{Topo} \times RF\_TX) \times \frac{1}{0.645} 
$$

$$
EF = EF_{Base} * RF\_NS * RF\_Till *RF\_CS * RF\_AM
$$


$$
EF = (EF_{Topo} \times RF\_TX) \times \frac{1}{0.645} * RF\_NS * RF\_Till *RF\_CS * RF\_AM
$$

**Variables**:

- $RF_{TX}$: A correction of the $EF_{Topo}$ in specific ecodistrict based on the soil texture 
- $RF_{CS}$: Reduction factor for Cropping System
- $RF_{NS}$: Reduction factor for N sourse 
- $RF_{AM}$: Reduction factor based on application method
- $RF_{Till}$: Tillage modifier based on tillage method


General formula:

$$
(N_2O_{N_{SNdirect}} + N_2O_{N_{CRNmindirect}} + N_2O_{N_{ONdirect}} + EF_{Topo} \times RF\_TX \times \frac{1}{0.645} \times RF\_NS \times RF\_Till \times RF\_CS \times RF\_AM \times ((AboveGround_{residue\_N} + BelowGround_{residue\_N}) \times area))
$$ 