---
title: "Parameter"
---

## GHG Emission Model Parameters

### Climate 

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| P | Annual growing season precipitation (May – October) | mm | $EF_{{CT}_{P}}$| Common | Default(based on ecodistrict level) & External Source (NASA)| 
| PE | Annual growing season potential evapotranspiration (May – October)  | mm  | $EF_{{CT}_{PE}}$| Common | Default(based on ecodistrict level) & External Source(NASA) | 

### Soil

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $FR_{Topo}$     | Fraction of land occupied by lower portions of landscape based on ecodistrict | unit | Emission Factor $EF_{Topo}$ (only for non-irrigated sites and dry environments) | Yes | Holos default (based on ecodistrict level)| 
| $RF_{TX}$    | a correction of the $EF_{Topo}$ in specific ecodistrict based on the soil texture  | unit  | $EF_{base}$| Yes| Holos default(based on ecodistrict level and soil type) | 
### Crop

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| Moisture | Moisture content of product | % | $C_p$ | Common | default Canada value (based on P and PE)| 
| $N_p$  | Nitrogen concentration in the product | kg N/kg | $Grain_N$ | Common | Holos default (based on P and PE)| 
| $N_s$  | Nitrogen concentration in the straw | kg N/kg | $Straw_N$ | Common | Holos default (based on P and PE)| 
| $N_r$      | Nitrogen concentration in the root | kg N/kg | $Root_N$ | Common | Holos default (based on P and PE)| 
| $N_e$      | Nitrogen concentration in the extraroot | kg N/kg | $Exudate_N$ | Common | Holos default (based on P and PE)| 
| $R_p$ | Relative biomass allocation coefficient for product | Unit |$C_s$, $C_r$,$C_e$ | Common | Holos default (based on P and PE)| 
| $R_r$ | Relative biomass allocation coefficient for roots | Unit |$C_r$| Common |Holos default(based on P and PE)| 
| $R_s$ | Relative biomass allocation coefficient for straw | Unit |$C_s$| Common | Holos default(based on P and PE)|
| $R_e$ | Relative biomass allocation coefficient for extra-root | Unit |$C_e$| Common | Holos default (based on P and PE)| 
| $C_{concentration}$ | Carbon concentration of all plant parts| kg C/kg |$C_p$| Common | Holos default(based crop group)| 
| $S_p$ | Percentage of product yield returned to soil| % |$C_p$,$C_{p\_to\_soil}$| Common | Holos default (based crop group)| 
| $S_s$ | Percentage of straw yield returned to soil| % |$Straw_N$,$C_s$| Common | Holos default(based crop group)| 
| $S_r$ | Percentage of root yield returned to soil| % |$Root_N$,$C_r$| Common | Holos default (based crop group)| 


### Modifiers(fertilizer)


| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| $RF_{CS}$ | Reduction factor for Cropping System| unit |$EF$| Common | Holos default (based on perennial or annual)| 
| $RF_{NS}$    | Reduction factor for N sourse (SN = Synthetic Nitrogen; ON = Organic Nitrogen; CRN = Crop Residue Nitrogen )  | unit  | $EF$| NA| Holos default (SN = Synthetic Nitrogen; ON = Organic Nitrogen; CRN = Crop Residue Nitrogen ) | 
| $RF_{AM}$    | Reduction factor based on application method| unit  | $EF$| NA| Holos default | 
| $RF_{Till}$    | Tillage modifier based on tillage method| unit  | $EF$| NA| Holos default (Conservation orvConventional Tillage)| 


### Farm

| **Parameter Name** | **Description** | **Units** | **Associate Formula/Variables(if applicable)** | **Region/Country Specific** | **Data Source** | 
|--------------------|-----------------|-----------|-----------------------------|----------------------------|------------------|
| Area | Numerical, total area of the farm | ha | $N_{CropResidues}$| Common | LiteFarm| 
| Yield | Numerical,the estimated yield | kg/ha  | $C_p$| Common | LiteFarm | 