---
title: "To-Do List"
format: html
---
## Task Table

|Task List| Assignee | START DATE   | DUE DATE     | NOTE |
|-------------------|----------|--------------|--------------|----------------|
| Literature Review (Aim for 10-15 papers)  | Caitie   | September 1st | December 1st | Preliminary Literature Review |
| Create Slides for the Solutions Scholar presentation | Caitie   | November 18th | December 5th |10 mins presentation |
| Add Notes to Literature Review  | Evan   | November 14th | November 15th|  |
| Summarization of key carbon credit and reporting requirements  | Evan | October 28th | November 29th| Focused on alignment of model variables, more to read regarding margin of error and timelines as well as reporting standards |
|Data Analysis - UBC Farm data | Talha, Evan  |  | December 6th|  |
|Input Progress Update to Project Webpage via Quarto | Anny  | October 1st | end of this project| Keep updates |
|Create a script to transfer the json file to a readable format | Sofia, Anny   | November 11th | November 29th| |
|Investigate all the default value in the Holos Model | Sofia, Anny | November 1st | December 5th| Focus on the Annual and Root crop for now|
|Summarize and Refine Clear List of Deliverables for the End of Semester | Whole Team  | October 1st | December 6th|  |
|Create Timeline for Solutions Scholar presentation in December  | Whole Team  | November 1st | December 1st|  |










